"""Internal fixture harness layer for Arkheionx (v3.9, additive, internal-only).

Provides deterministic fixture ID utilities and the pure fixture dataclasses that
later v3.9 agents use to register real protocol fixtures, run the core pipeline
over them, and benchmark deterministic outputs. This package is internal
infrastructure: it is not a public API, adds no CLI command, changes no public
artifact shape or schema, performs no filesystem, network, subprocess, RPC,
fork-url, live-chain, key-handling, or exploit behavior, and writes nothing on
import. It organizes local/static review and benchmark context only -- never a
confirmed vulnerability, a final severity, an audit outcome, or submission
readiness; a fixture passing never proves safety and a fixture failing never
proves a vulnerability.
"""
from __future__ import annotations

from .ids import (
    canonical_fixture_seed,
    fixture_artifact_id,
    fixture_id,
    fixture_result_id,
    fixture_run_id,
    fixture_snapshot_id,
    normalize_fixture_path,
    short_fixture_hash,
    slugify_fixture_token,
)
from .model import (
    SCHEMA_VERSION,
    FIXTURE_CATEGORY_ERC20,
    FIXTURE_CATEGORY_LENDING_VAULT,
    FIXTURE_CATEGORY_STAKING_REWARD,
    FIXTURE_CATEGORY_AMM_SWAP,
    FIXTURE_CATEGORY_ORACLE_DEPENDENT,
    FIXTURE_CATEGORY_UPGRADEABLE_PROXY,
    FIXTURE_CATEGORY_BRIDGE_MESSAGE,
    FIXTURE_CATEGORY_LIQUIDATION_BORROW_REPAY,
    FIXTURE_CATEGORY_MISC,
    FIXTURE_CATEGORY_VALUES,
    FIXTURE_CATEGORY_DESCRIPTIONS,
    FIXTURE_ARTIFACT_SOURCE,
    FIXTURE_ARTIFACT_REVIEW_MAP,
    FIXTURE_ARTIFACT_PROTOCOL_MODEL,
    FIXTURE_ARTIFACT_LOCAL_VALIDATION,
    FIXTURE_ARTIFACT_PROTOCOL_GRAPH,
    FIXTURE_ARTIFACT_EVIDENCE,
    FIXTURE_ARTIFACT_REPORT,
    FIXTURE_ARTIFACT_REVIEW_PACKAGE,
    FIXTURE_ARTIFACT_SNAPSHOT,
    FIXTURE_ARTIFACT_UNKNOWN,
    FIXTURE_ARTIFACT_KIND_VALUES,
    FIXTURE_RUN_PLANNED,
    FIXTURE_RUN_READY,
    FIXTURE_RUN_EXECUTED,
    FIXTURE_RUN_PARTIAL,
    FIXTURE_RUN_FAILED,
    FIXTURE_RUN_SKIPPED,
    FIXTURE_RUN_STATUS_VALUES,
    FIXTURE_RESULT_OBSERVED,
    FIXTURE_RESULT_MATCHED_SNAPSHOT,
    FIXTURE_RESULT_DRIFT_DETECTED,
    FIXTURE_RESULT_NEEDS_REVIEW,
    FIXTURE_RESULT_FAILED,
    FIXTURE_RESULT_SKIPPED,
    FIXTURE_RESULT_STATUS_VALUES,
    BENCHMARK_DIMENSION_ID_STABILITY,
    BENCHMARK_DIMENSION_JSON_STABILITY,
    BENCHMARK_DIMENSION_GRAPH_COUNTS,
    BENCHMARK_DIMENSION_CROSSREF_OUTCOMES,
    BENCHMARK_DIMENSION_EXPORT_CHECKSUM,
    BENCHMARK_DIMENSION_JSON_PURITY,
    BENCHMARK_DIMENSION_NO_OVERCLAIM,
    BENCHMARK_DIMENSION_REVIEW_CONTEXT,
    BENCHMARK_DIMENSION_VALUES,
    FixtureSafetyBoundary,
    ProtocolFixture,
    FixtureArtifactRef,
    FixtureRun,
    FixtureResult,
    FixtureSnapshotRef,
    FixtureSuite,
    build_protocol_fixture,
    build_fixture_suite,
    fixture_suite_id,
    fixture_harness_to_dict,
)
from .fixtures import (
    SET1_ROOT,
    SET1_SUITE_NAME,
    set1_fixture_definitions,
    set1_fixture_artifacts,
    build_set1_fixture_suite,
    SET2_ROOT,
    SET2_SUITE_NAME,
    set2_fixture_definitions,
    set2_fixture_artifacts,
    build_set2_fixture_suite,
    SET3_ROOT,
    SET3_SUITE_NAME,
    set3_fixture_definitions,
    set3_fixture_artifacts,
    build_set3_fixture_suite,
    ALL_SUITE_NAME,
    all_fixture_definitions,
    all_fixture_artifacts,
    build_all_fixture_suite,
)
from .runner import (
    build_fixture_source_fingerprints,
    run_fixture_benchmark,
    run_fixture_benchmark_suite,
    benchmark_set1_fixture_suite,
    benchmark_all_fixture_suite,
)
from .snapshots import (
    SNAPSHOT_SCHEMA_VERSION,
    SET1_SNAPSHOT_RELPATH,
    ALL_SNAPSHOT_RELPATH,
    build_set1_benchmark_snapshot,
    load_set1_benchmark_snapshot,
    compare_set1_benchmark_snapshot,
    build_all_benchmark_snapshot,
    load_all_benchmark_snapshot,
    compare_all_benchmark_snapshot,
    snapshot_to_jsonable,
)
from .crossref import (
    build_fixture_benchmark_crossref,
    build_set1_fixture_crossref,
    build_all_fixture_crossref,
)

__all__ = [
    "SCHEMA_VERSION",
    # ID helpers
    "canonical_fixture_seed",
    "short_fixture_hash",
    "slugify_fixture_token",
    "normalize_fixture_path",
    "fixture_id",
    "fixture_artifact_id",
    "fixture_run_id",
    "fixture_result_id",
    "fixture_snapshot_id",
    # Categories
    "FIXTURE_CATEGORY_ERC20",
    "FIXTURE_CATEGORY_LENDING_VAULT",
    "FIXTURE_CATEGORY_STAKING_REWARD",
    "FIXTURE_CATEGORY_AMM_SWAP",
    "FIXTURE_CATEGORY_ORACLE_DEPENDENT",
    "FIXTURE_CATEGORY_UPGRADEABLE_PROXY",
    "FIXTURE_CATEGORY_BRIDGE_MESSAGE",
    "FIXTURE_CATEGORY_LIQUIDATION_BORROW_REPAY",
    "FIXTURE_CATEGORY_MISC",
    "FIXTURE_CATEGORY_VALUES",
    "FIXTURE_CATEGORY_DESCRIPTIONS",
    # Artifact kinds
    "FIXTURE_ARTIFACT_SOURCE",
    "FIXTURE_ARTIFACT_REVIEW_MAP",
    "FIXTURE_ARTIFACT_PROTOCOL_MODEL",
    "FIXTURE_ARTIFACT_LOCAL_VALIDATION",
    "FIXTURE_ARTIFACT_PROTOCOL_GRAPH",
    "FIXTURE_ARTIFACT_EVIDENCE",
    "FIXTURE_ARTIFACT_REPORT",
    "FIXTURE_ARTIFACT_REVIEW_PACKAGE",
    "FIXTURE_ARTIFACT_SNAPSHOT",
    "FIXTURE_ARTIFACT_UNKNOWN",
    "FIXTURE_ARTIFACT_KIND_VALUES",
    # Run statuses
    "FIXTURE_RUN_PLANNED",
    "FIXTURE_RUN_READY",
    "FIXTURE_RUN_EXECUTED",
    "FIXTURE_RUN_PARTIAL",
    "FIXTURE_RUN_FAILED",
    "FIXTURE_RUN_SKIPPED",
    "FIXTURE_RUN_STATUS_VALUES",
    # Result statuses
    "FIXTURE_RESULT_OBSERVED",
    "FIXTURE_RESULT_MATCHED_SNAPSHOT",
    "FIXTURE_RESULT_DRIFT_DETECTED",
    "FIXTURE_RESULT_NEEDS_REVIEW",
    "FIXTURE_RESULT_FAILED",
    "FIXTURE_RESULT_SKIPPED",
    "FIXTURE_RESULT_STATUS_VALUES",
    # Benchmark dimensions
    "BENCHMARK_DIMENSION_ID_STABILITY",
    "BENCHMARK_DIMENSION_JSON_STABILITY",
    "BENCHMARK_DIMENSION_GRAPH_COUNTS",
    "BENCHMARK_DIMENSION_CROSSREF_OUTCOMES",
    "BENCHMARK_DIMENSION_EXPORT_CHECKSUM",
    "BENCHMARK_DIMENSION_JSON_PURITY",
    "BENCHMARK_DIMENSION_NO_OVERCLAIM",
    "BENCHMARK_DIMENSION_REVIEW_CONTEXT",
    "BENCHMARK_DIMENSION_VALUES",
    # Dataclasses
    "FixtureSafetyBoundary",
    "ProtocolFixture",
    "FixtureArtifactRef",
    "FixtureRun",
    "FixtureResult",
    "FixtureSnapshotRef",
    "FixtureSuite",
    # Builder helpers + serializer
    "build_protocol_fixture",
    "build_fixture_suite",
    "fixture_suite_id",
    "fixture_harness_to_dict",
    # Set 1 fixture registry
    "SET1_ROOT",
    "SET1_SUITE_NAME",
    "set1_fixture_definitions",
    "set1_fixture_artifacts",
    "build_set1_fixture_suite",
    # Set 2 fixture registry
    "SET2_ROOT",
    "SET2_SUITE_NAME",
    "set2_fixture_definitions",
    "set2_fixture_artifacts",
    "build_set2_fixture_suite",
    # Set 3 fixture registry
    "SET3_ROOT",
    "SET3_SUITE_NAME",
    "set3_fixture_definitions",
    "set3_fixture_artifacts",
    "build_set3_fixture_suite",
    # Combined all-fixtures registry
    "ALL_SUITE_NAME",
    "all_fixture_definitions",
    "all_fixture_artifacts",
    "build_all_fixture_suite",
    # Fixture benchmark runner
    "build_fixture_source_fingerprints",
    "run_fixture_benchmark",
    "run_fixture_benchmark_suite",
    "benchmark_set1_fixture_suite",
    "benchmark_all_fixture_suite",
    # Benchmark snapshot baselines
    "SNAPSHOT_SCHEMA_VERSION",
    "SET1_SNAPSHOT_RELPATH",
    "ALL_SNAPSHOT_RELPATH",
    "build_set1_benchmark_snapshot",
    "load_set1_benchmark_snapshot",
    "compare_set1_benchmark_snapshot",
    "build_all_benchmark_snapshot",
    "load_all_benchmark_snapshot",
    "compare_all_benchmark_snapshot",
    "snapshot_to_jsonable",
    # Fixture benchmark crossrefs
    "build_fixture_benchmark_crossref",
    "build_set1_fixture_crossref",
    "build_all_fixture_crossref",
]
