"""Complete Review package generator for the v6 Evidence Graph layer (headline).

Builds a complete, local, vendor-agnostic review package under one folder. It
composes the v4 review map, the v5 blind-spot / criticality / counterfactual
engine, and the v6 evidence graph, interaction matrix, and unresolved map, then
adds a README, a model-agnostic agent input, a human review checklist, and a
JSON manifest.

The pack is model-agnostic on purpose: it speaks of an "AI agent", "review
agent", "human reviewer", and "local test runner", never a specific vendor. It
is local/static and makes no vulnerability claims. Human review is required.
"""
from __future__ import annotations

import json
from pathlib import Path

from arkheionx.blind_spots.engine import (
    build_blind_spot_map,
    build_counterfactual_plan,
    build_criticality_map,
)
from arkheionx.blind_spots.pack import render_review_map_summary
from arkheionx.blind_spots.render import (
    render_blind_spots_md,
    render_counterfactuals_md,
    render_criticality_map_md,
)
from arkheionx.research import build_case_study_from_review_map, render_case_study_md
from arkheionx.research.surfaces import build_research_surfaces
from arkheionx.review_map.model import ReviewMap

from . import models as m, render
from .builder import build_evidence_graph
from .interactions import build_interaction_matrix
from .unresolved import build_unresolved_map


def _write(path: Path, content: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not content.endswith("\n"):
        content += "\n"
    path.write_text(content, encoding="utf-8")
    return str(path)


_MARKDOWN_FILES = (
    "00-README.md", "01-review-map-summary.md", "02-blind-spots-summary.md",
    "03-criticality-summary.md", "04-counterfactuals-summary.md", "05-evidence-graph.md",
    "06-interaction-matrix.md", "07-unresolved-surfaces.md", "08-agent-input.md",
    "09-human-review-checklist.md", "10-case-study-template.md",
)
_JSON_FILES = (
    "evidence-graph.json", "interaction-matrix.json", "unresolved-map.json",
    "complete-review.json", "manifest.json",
)
COMMANDS_REPRESENTED = ["review-map", "blind-spots", "criticality-map", "counterfactuals",
                        "evidence-graph", "interaction-matrix", "unresolved-map", "complete-review"]


def render_readme(rm: ReviewMap, package_version: str) -> str:
    return "\n".join([
        "# Arkheionx Complete Review Package",
        "",
        "> Local/static review package. Nothing here is a vulnerability, a severity, or a",
        "> confirmed finding. Evidence state is not a vulnerability claim. Human review required.",
        "",
        "## What this package is",
        "",
        "A complete local review package for a single repository. It shows, in one place:",
        "what value paths exist, where the likely blind spots are, what criticality potential",
        "exists, which counterfactuals to test, **what evidence exists**, **what remains",
        "unresolved**, and **which interactions still lack tests**. It is built to make a large",
        "DeFi repository easier to review. It does not predict bugs and does not replace an audit.",
        "",
        f"- Repository: `{rm.repo_path}`",
        f"- Mode: {rm.mode} (heuristic)",
        f"- Generated by: ArkheionX v{package_version} Evidence Graph + Interaction Matrix",
        "",
        "## What this package is not",
        "",
        "- Not a vulnerability report. An evidence state is not a vulnerability claim.",
        "- Not a severity assessment. Criticality potential and interaction priority are not severity.",
        "- Not a confirmation. `confirmed-candidate` is not a confirmed vulnerability.",
        "- Not an audit, and not a guarantee of coverage or safety.",
        "",
        "## Files in this package",
        "",
        "- `00-README.md` — this file.",
        "- `01-review-map-summary.md` — protocol structure, value paths, assumptions, test gaps.",
        "- `02-blind-spots-summary.md` — likely blind-spot candidates, ranked.",
        "- `03-criticality-summary.md` — criticality potential (blast radius) across surfaces.",
        "- `04-counterfactuals-summary.md` — testable \"what if this assumption is false?\" prompts.",
        "- `05-evidence-graph.md` — every important surface classified into an evidence state.",
        "- `06-interaction-matrix.md` — combinations of surfaces that may hide bugs when tested together.",
        "- `07-unresolved-surfaces.md` — everything important that local evidence does not close.",
        "- `08-agent-input.md` — a scoped, model-agnostic task to hand to a review agent.",
        "- `09-human-review-checklist.md` — the checklist a human completes before ending review.",
        "- `10-case-study-template.md` — a sanitized research-session report template.",
        "- `manifest.json` — machine-readable index of this package.",
        "- `*.json` — machine-readable evidence graph, interaction matrix, and unresolved map.",
        "",
        "## Which files matter first",
        "",
        "1. Read `01-review-map-summary.md` to understand how value moves.",
        "2. Read `05-evidence-graph.md` to see what is tested and what is unresolved.",
        "3. Read `06-interaction-matrix.md` and `07-unresolved-surfaces.md` to decide where to look.",
        "",
        "## Which file to give to an AI agent",
        "",
        "Give the agent `08-agent-input.md`. It is scoped, vendor-neutral, and asks the agent to",
        "write local tests for unresolved surfaces and interactions, not to claim findings.",
        "",
        "## Which file a human should review",
        "",
        "A human completes `09-human-review-checklist.md`. A finding is only ever confirmed by a",
        "human with independent local proof.",
        "",
        "## Safety boundaries",
        "",
        "Local/static only. No RPC, no live-chain calls, no private keys, no exploit automation,",
        "no auto-submit, no severity. Evidence state is not a vulnerability claim. Unresolved does",
        "not mean vulnerable. ArkheionX makes no vulnerability claims. Human review is required.",
        "",
    ]) + "\n"


def render_agent_input(evidence_graph: dict, matrix: dict, unresolved: dict,
                       counterfactuals: dict) -> str:
    out = [
        "# Agent Input — Scoped Review Task",
        "",
        "> Model-agnostic. Written for any AI agent, review agent, or human reviewer working",
        "> with a local test runner. This is review context, not a finding. Human review required.",
        "",
        "## Task framing",
        "",
        "You are a review agent working on a local Solidity/Foundry repository. Your job is to",
        "turn the unresolved surfaces and interactions below into **local tests** and record what",
        "you find. You must not claim a vulnerability, assign a severity, or submit anything. A",
        "human makes every final call.",
        "",
        "## Rules of engagement",
        "",
        "- Work only on the local repository. No RPC, no live-chain, no deployed-contract access.",
        "- For each item, write a local test that asserts the suggested invariant (or records how it fails).",
        "- If an invariant holds, record the item as rejected-with-evidence — that is useful research memory.",
        "- If a test suggests an issue, record it as a candidate for human review — never as a confirmed bug.",
        "- Do not claim severity. Do not claim a vulnerability. Do not submit anything.",
        "",
        "## Top unresolved surfaces",
        "",
    ]
    surfaces = unresolved["unresolved_surfaces"][:10]
    if surfaces:
        for u in surfaces:
            out += [
                f"### {u['id']} — {u['surface']}",
                f"- Why it matters: {u['why_important']}",
                f"- Evidence state: {u['evidence_state']} (strength {u['evidence_strength']})",
                f"- Suggested local test: {u['suggested_test'] or '—'}",
                f"- Missing evidence: {', '.join(u['missing_evidence']) or '—'}",
                "- Stop condition: stop when the suggested test passes (invariant holds) or clearly fails locally.",
                "- Do not claim: this is a review candidate, not a finding.",
                "",
            ]
    else:
        out.append("_No high-impact unresolved surfaces — confirm coverage and move on._\n")
    out += ["## Top unresolved interactions", ""]
    interactions = unresolved["unresolved_interactions"][:10]
    if interactions:
        for u in interactions:
            out += [
                f"### {u['id']} — {u['interaction']}",
                f"- Surfaces: {', '.join(u['surfaces'])}",
                f"- Why it matters: {u['why_important']}",
                f"- Suggested local invariant: {u['suggested_test']}",
                "- Evidence required: a local test that drives the combination and asserts the invariant.",
                "- Stop condition: stop when the invariant is shown to hold or fail locally.",
                "- Do not claim: this is a review candidate, not a finding.",
                "",
            ]
    else:
        out.append("_No high-impact unresolved interactions — confirm coverage and move on._\n")
    out += ["## Counterfactuals to test", ""]
    for cf in counterfactuals["counterfactuals"][:10]:
        tgt = f" (`{cf['target']}`)" if cf.get("target") else ""
        out.append(f"- {cf['id']}{tgt}: {cf['what_if_false']}")
    out += [
        "",
        "## Do-not-claim rules",
        "",
    ]
    for line in m.DO_NOT_CLAIM:
        out.append(f"- {line}")
    out += ["", "---", "", evidence_graph["safety"]["disclaimer"], ""]
    return "\n".join(out) + "\n"


def render_human_review_checklist() -> str:
    items = [
        "Is every high-impact surface classified into an evidence state?",
        "Is every high-impact interaction classified?",
        "Has every unresolved item been reviewed (or explicitly deferred with a reason)?",
        "Does every confirmed-candidate have a local proof-of-concept test? (No PoC, no claim.)",
        "Does every rejected hypothesis have recorded local evidence?",
        "Has every potential finding been checked for scope (is the target in scope)?",
        "Has every potential finding been checked for duplicate risk?",
        "Does every potential finding have a concrete impact a human can articulate?",
        "Has no blind-spot output been submitted as a finding?",
        "Has no criticality potential been submitted as a severity?",
        "Has no evidence state been treated as final without human review?",
    ]
    out = [
        "# Human Review Checklist",
        "",
        "> Complete this before ending the review. A finding is only ever confirmed by a human",
        "> with independent local proof. Evidence state is not a vulnerability claim.",
        "",
    ]
    for item in items:
        out.append(f"- [ ] {item}")
    out += [
        "",
        "## Boundary",
        "",
    ]
    for line in m.BOUNDARY_LINES:
        out.append(f"- {line}")
    out.append("")
    return "\n".join(out) + "\n"


def build_complete_review(rm: ReviewMap, root, out_dir, *, package_version: str,
                          source_files: int = 0, test_files: int = 0,
                          memory: dict[str, str] | None = None, write: bool = True) -> dict:
    """Build all package payloads, write every file (unless ``write`` is False),
    and return the manifest + paths."""
    out_dir = Path(out_dir)
    memory = memory or {}
    surfaces = build_research_surfaces(rm, root)

    blind_spots = build_blind_spot_map(rm, surfaces, source_files=source_files, test_files=test_files)
    criticality = build_criticality_map(rm, surfaces, source_files=source_files, test_files=test_files)
    counterfactuals = build_counterfactual_plan(rm, surfaces, source_files=source_files, test_files=test_files)
    evidence_graph = build_evidence_graph(rm, surfaces, source_files=source_files, test_files=test_files,
                                          memory=memory, package_version=package_version)
    matrix = build_interaction_matrix(rm, surfaces, source_files=source_files, test_files=test_files,
                                      memory=memory, package_version=package_version)
    unresolved = build_unresolved_map(rm, surfaces, source_files=source_files, test_files=test_files,
                                      memory=memory, package_version=package_version)
    case_study = build_case_study_from_review_map(rm, root)

    contents = {
        "00-README.md": render_readme(rm, package_version),
        "01-review-map-summary.md": render_review_map_summary(rm),
        "02-blind-spots-summary.md": render_blind_spots_md(blind_spots),
        "03-criticality-summary.md": render_criticality_map_md(criticality),
        "04-counterfactuals-summary.md": render_counterfactuals_md(counterfactuals),
        "05-evidence-graph.md": render.render_evidence_graph_md(evidence_graph),
        "06-interaction-matrix.md": render.render_interaction_matrix_md(matrix),
        "07-unresolved-surfaces.md": render.render_unresolved_map_md(unresolved),
        "08-agent-input.md": render_agent_input(evidence_graph, matrix, unresolved, counterfactuals),
        "09-human-review-checklist.md": render_human_review_checklist(),
        "10-case-study-template.md": render_case_study_md(case_study),
    }

    complete_review_json = {
        "schema_version": m.SCHEMA_VERSION,
        "package_version": package_version,
        "command": "complete-review",
        "repo_path": rm.repo_path,
        "mode": rm.mode,
        "evidence_graph": evidence_graph,
        "interaction_matrix": matrix,
        "unresolved_map": unresolved,
    }
    json_payloads = {
        "evidence-graph.json": evidence_graph,
        "interaction-matrix.json": matrix,
        "unresolved-map.json": unresolved,
        "complete-review.json": complete_review_json,
    }

    evidence_node_count = len(evidence_graph["nodes"])
    interaction_count = matrix["matrix_summary"]["total_interactions"]
    unresolved_surface_count = len(unresolved["unresolved_surfaces"])
    unresolved_interaction_count = len(unresolved["unresolved_interactions"])

    manifest = {
        "schema_version": m.SCHEMA_VERSION,
        "kind": m.KIND_COMPLETE_REVIEW_MANIFEST,
        "command": "complete-review",
        "generated_at": rm.generated_at,
        "repo_path": rm.repo_path,
        "mode": rm.mode,
        "package_version": package_version,
        "commands_represented": list(COMMANDS_REPRESENTED),
        "artifact_list": list(_MARKDOWN_FILES) + list(_JSON_FILES),
        "evidence_node_count": evidence_node_count,
        "interaction_count": interaction_count,
        "unresolved_surface_count": unresolved_surface_count,
        "unresolved_interaction_count": unresolved_interaction_count,
        "evidence_state_summary": evidence_graph["evidence_state_summary"],
        "safety_flags": {
            "local_static_only": True,
            "no_rpc": True,
            "no_live_chain": True,
            "no_secrets": True,
            "no_exploit_automation": True,
            "no_auto_submit": True,
            "no_severity": True,
            "no_vulnerability_claims": True,
            "vendor_agnostic": True,
            "human_review_required": True,
            "disclaimer": rm.safety.disclaimer,
        },
        "human_review_required": True,
    }

    written: dict[str, str] = {}
    for name in _MARKDOWN_FILES:
        written[name] = _write(out_dir / name, contents[name]) if write else str(out_dir / name)
    for name, payload in json_payloads.items():
        if name == "manifest.json":
            continue
        written[name] = _write(out_dir / name, json.dumps(payload, indent=2)) if write else str(out_dir / name)
    written["manifest.json"] = (
        _write(out_dir / "manifest.json", json.dumps(manifest, indent=2)) if write else str(out_dir / "manifest.json"))

    return {"manifest": manifest, "written": written, "out_dir": str(out_dir)}


def build_complete_review_from_review_map(rm: ReviewMap, root, out_dir, *, package_version: str,
                                          source_files: int = 0, test_files: int = 0,
                                          memory: dict[str, str] | None = None, write: bool = True) -> dict:
    return build_complete_review(rm, root, out_dir, package_version=package_version,
                                 source_files=source_files, test_files=test_files,
                                 memory=memory, write=write)
