"""Canonical root-cause families and compatibility aliases."""
from __future__ import annotations

ROUNDING_REPAYMENT_RECONCILIATION = "ROUNDING_REPAYMENT_RECONCILIATION"
ROUNDING_SHARE_ASSET_RECONCILIATION = "ROUNDING_SHARE_ASSET_RECONCILIATION"
LENDER_CONSENT_VALUE_FIELD_BINDING = "LENDER_CONSENT_VALUE_FIELD_BINDING"
SIGNATURE_OPERATION_BINDING = "SIGNATURE_OPERATION_BINDING"
SIGNATURE_REPLAY_DOMAIN = "SIGNATURE_REPLAY_DOMAIN"
THRESHOLD_AUTHORIZATION_BYPASS = "THRESHOLD_AUTHORIZATION_BYPASS"
NONCE_SEQUENCE_REPLAY = "NONCE_SEQUENCE_REPLAY"
DELEGATECALL_STORAGE_CONTROL = "DELEGATECALL_STORAGE_CONTROL"
ACTUAL_RECEIVED_VS_CREDITED = "ACTUAL_RECEIVED_VS_CREDITED"
ORACLE_DECIMAL_NORMALIZATION = "ORACLE_DECIMAL_NORMALIZATION"
ORACLE_STALENESS_VALIDATION = "ORACLE_STALENESS_VALIDATION"
CROSS_CHAIN_SUPPLY_CONSERVATION = "CROSS_CHAIN_SUPPLY_CONSERVATION"
DEPOSIT_CONTEXT_COMPLETENESS = "DEPOSIT_CONTEXT_COMPLETENESS"
DEPOSIT_DOUBLE_CONSUMPTION = "DEPOSIT_DOUBLE_CONSUMPTION"
COLLATERAL_STATUS_RELEASE = "COLLATERAL_STATUS_RELEASE"
BORROW_CONSERVATION = "BORROW_CONSERVATION"
VAULT_SHARE_INFLATION = "VAULT_SHARE_INFLATION"
RECEIVER_AUTHORIZATION = "RECEIVER_AUTHORIZATION"
FACTORY_INITIALIZATION_TAKEOVER = "FACTORY_INITIALIZATION_TAKEOVER"
FORCED_VALUE_TRANSFER_NO_LOGIC_FLAW = "FORCED_VALUE_TRANSFER_NO_LOGIC_FLAW"
TRUSTED_ROLE_ASSUMPTION = "TRUSTED_ROLE_ASSUMPTION"
OFFCHAIN_VALIDATION_OMISSION = "OFFCHAIN_VALIDATION_OMISSION"
KEY_REUSE_REPLAY = "KEY_REUSE_REPLAY"
GAS_ONLY = "GAS_ONLY"
PRECISION_DUST_ONLY = "PRECISION_DUST_ONLY"
NO_ATTACKER_PROFIT = "NO_ATTACKER_PROFIT"
VICTIM_OPT_IN_TERMS = "VICTIM_OPT_IN_TERMS"
UNKNOWN = "UNKNOWN"

ALL = (
    ROUNDING_REPAYMENT_RECONCILIATION,
    ROUNDING_SHARE_ASSET_RECONCILIATION,
    LENDER_CONSENT_VALUE_FIELD_BINDING,
    SIGNATURE_OPERATION_BINDING,
    SIGNATURE_REPLAY_DOMAIN,
    THRESHOLD_AUTHORIZATION_BYPASS,
    NONCE_SEQUENCE_REPLAY,
    DELEGATECALL_STORAGE_CONTROL,
    ACTUAL_RECEIVED_VS_CREDITED,
    ORACLE_DECIMAL_NORMALIZATION,
    ORACLE_STALENESS_VALIDATION,
    CROSS_CHAIN_SUPPLY_CONSERVATION,
    DEPOSIT_CONTEXT_COMPLETENESS,
    DEPOSIT_DOUBLE_CONSUMPTION,
    COLLATERAL_STATUS_RELEASE,
    BORROW_CONSERVATION,
    VAULT_SHARE_INFLATION,
    RECEIVER_AUTHORIZATION,
    FACTORY_INITIALIZATION_TAKEOVER,
    FORCED_VALUE_TRANSFER_NO_LOGIC_FLAW,
    TRUSTED_ROLE_ASSUMPTION,
    OFFCHAIN_VALIDATION_OMISSION,
    KEY_REUSE_REPLAY,
    GAS_ONLY,
    PRECISION_DUST_ONLY,
    NO_ATTACKER_PROFIT,
    VICTIM_OPT_IN_TERMS,
    UNKNOWN,
)

ALIASES = {
    "DEBT_REPAYMENT_RECONCILIATION": ROUNDING_REPAYMENT_RECONCILIATION,
    "VAULT_SHARE_ASSET_RECONCILIATION": ROUNDING_SHARE_ASSET_RECONCILIATION,
    "LENDER_CONSENT_VALUE_AFFECTING_CALLDATA": LENDER_CONSENT_VALUE_FIELD_BINDING,
    "SWAP_ACTUAL_RECEIVED_VS_CREDITED": ACTUAL_RECEIVED_VS_CREDITED,
    "DEPOSIT_CONSUMPTION": DEPOSIT_DOUBLE_CONSUMPTION,
}


def canonical(value: str) -> str:
    family = (value or "").strip().upper()
    if not family:
        return UNKNOWN
    return ALIASES.get(family, family if family in ALL else UNKNOWN)
