"""Research pack generator for the v5 Blind Spot Intelligence layer (headline).

Builds a complete, local, vendor-agnostic bug bounty research pack under one
folder. It composes the v5 blind-spot / criticality / counterfactual engine with
the v4.1 research-memory renderers (agent brief, hypotheses, case study) and adds
a README, a review-map summary, an evidence-log template, and a do-not-claim
file plus a JSON manifest.

The pack is model-agnostic and vendor-agnostic on purpose: it speaks of an "AI
agent", "review agent", "human reviewer", "researcher", and "local test runner",
never a specific product. It is local/static and makes no vulnerability claims.
"""
from __future__ import annotations

import json
from pathlib import Path

from arkheionx.research import (
    build_agent_brief_from_review_map,
    build_case_study_from_review_map,
    build_hypothesis_log_from_review_map,
    render_agent_brief_md,
)
from arkheionx.research.case_study import render_case_study_md
from arkheionx.research.hypothesis_log import render_hypothesis_log_md
from arkheionx.review_map.model import ReviewMap

from . import models as m
from . import render
from .engine import (
    build_blind_spot_map_from_review_map,
    build_criticality_map_from_review_map,
    build_counterfactual_plan_from_review_map,
)
from .json_output import default_research_pack_dir  # re-exported for the CLI


def _write(path: Path, content: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not content.endswith("\n"):
        content += "\n"
    path.write_text(content, encoding="utf-8")
    return str(path)


# --------------------------------------------------------------------------
# Bespoke pack documents
# --------------------------------------------------------------------------
def render_pack_readme(rm: ReviewMap, package_version: str) -> str:
    return "\n".join([
        "# Arkheionx Research Pack",
        "",
        "> Local/static heuristic research pack. Nothing here is a vulnerability,",
        "> a severity, or a confirmed finding. Human review is required.",
        "",
        "## What this pack is",
        "",
        "This is a local bug bounty / pre-audit research pack for a single repository.",
        "It tells a human reviewer or an AI agent **where to spend review time first**:",
        "high-impact surfaces with weak review evidence, the assumptions that guard them,",
        "and the counterfactual questions worth testing. It does not predict bugs and does",
        "not replace an audit.",
        "",
        f"- Repository: `{rm.repo_path}`",
        f"- Mode: {rm.mode} (heuristic)",
        f"- Generated by: ArkheionX v{package_version} Blind Spot Intelligence",
        "",
        "## Files in this pack",
        "",
        "- `00-README.md` — this file.",
        "- `01-review-map-summary.md` — protocol structure, value paths, assumptions, test gaps.",
        "- `02-blind-spots.md` — likely blind-spot candidates, ranked by a transparent score.",
        "- `03-criticality-map.md` — criticality potential (blast radius) across surfaces.",
        "- `04-counterfactuals.md` — testable \"what if this assumption is false?\" prompts.",
        "- `05-agent-brief.md` — a scoped brief to hand to an AI agent or reviewer.",
        "- `06-hypotheses.md` — a hypothesis log template (every entry starts `open`).",
        "- `07-evidence-log.md` — record tests, results, rejections, and human decisions here.",
        "- `08-do-not-claim.md` — the boundary: what must never be claimed.",
        "- `09-case-study-template.md` — a sanitized research-session report template.",
        "- `manifest.json` — machine-readable index of this pack.",
        "- `*.json` — machine-readable versions of the documents above.",
        "",
        "## Suggested workflow",
        "",
        "1. Read `01-review-map-summary.md` to understand how value moves.",
        "2. Read `02-blind-spots.md` and `03-criticality-map.md` to decide where to look first.",
        "3. Give `05-agent-brief.md` (and `04-counterfactuals.md`) to a review agent or reviewer.",
        "4. Turn the highest-priority counterfactuals into local tests with a local test runner.",
        "5. Record every test, result, and rejection in `07-evidence-log.md`.",
        "6. A finding is only ever confirmed by a human with independent local proof.",
        "",
        "## Which file to give to an AI agent",
        "",
        "Give the agent `05-agent-brief.md` plus `04-counterfactuals.md`. They are scoped,",
        "safe, and vendor-neutral. Ask the agent to write local tests for the counterfactuals,",
        "not to claim findings.",
        "",
        "## Which file to edit after tests",
        "",
        "Edit `07-evidence-log.md` (and `06-hypotheses.md` statuses) after each local test.",
        "Record the command you ran, the result, and — if the invariant held — the rejection",
        "reason. A rejected hypothesis is useful research memory.",
        "",
        "## Safety boundaries",
        "",
        "Local/static only. No RPC, no live-chain calls, no private keys, no secrets, no",
        "exploit automation, no transaction broadcasting, no auto-submit, no severity. Blind",
        "spot candidates and criticality potential are heuristics, not vulnerabilities or",
        "severities. ArkheionX makes no vulnerability claims. Human review is required.",
        "",
    ]) + "\n"


def render_review_map_summary(rm: ReviewMap) -> str:
    s = rm.summary
    out = [
        "# Review Map Summary",
        "",
        "> Local/static heuristic review surface. Review guidance only, not findings.",
        "",
        f"- Repository: `{rm.repo_path}`",
        f"- Mode: {rm.mode} (heuristic)",
        f"- Protocol types: {', '.join(s.protocol_types) or 'generic'}",
        f"- Contracts: {s.contracts_analyzed} · Functions: {s.functions_mapped}",
        f"- Value paths: {s.value_paths} · Assumptions: {s.assumptions} · Test gaps: {s.test_gaps}",
        "",
        "## Inspect-first surfaces (review order, not severity)",
        "",
    ]
    notes = rm.reviewer_notes[:8]
    if notes:
        for n in notes:
            out.append(f"- `{n.title}` — {n.body}")
    else:
        out.append("_No inspect-first reviewer notes surfaced._")
    out += ["", "## Value paths", ""]
    if rm.value_paths:
        for vp in rm.value_paths[:10]:
            out.append(f"- `{vp.id}` — {vp.label} (coverage hint: {vp.test_coverage_hint})")
    else:
        out.append("_No value paths surfaced._")
    out += ["", "## Assumptions (unverified guarding properties)", ""]
    if rm.assumptions:
        for a in rm.assumptions:
            out.append(f"- `{a.id}` [{a.category}] {a.title} — used by: {', '.join(a.used_by) or '—'}")
    else:
        out.append("_No assumptions surfaced._")
    out += ["", "## Test gaps", ""]
    if rm.test_gaps:
        for g in rm.test_gaps[:12]:
            out.append(f"- `{g.id}` {g.related_function} — {g.rationale or g.title}")
    else:
        out.append("_No test gaps surfaced._")
    out += ["", "---", "", rm.safety.disclaimer, ""]
    return "\n".join(out) + "\n"


def render_evidence_log_template() -> str:
    return "\n".join([
        "# Evidence Log",
        "",
        "> Record local test evidence here. A hypothesis is not a finding. A finding is",
        "> only ever confirmed by a human with independent local proof.",
        "",
        "Fill one entry per hypothesis or counterfactual you test. Keep evidence local.",
        "",
        "## Entry template",
        "",
        "- **Hypothesis ID**: (e.g. HYP-001 or CF-001)",
        "- **Test file**: (path to the local test you wrote)",
        "- **Command run**: (the exact local test command)",
        "- **Result**: (pass / fail / inconclusive)",
        "- **Evidence summary**: (what the test showed, locally)",
        "- **Rejection reason**: (if the invariant held — which invariant, under what conditions)",
        "- **Confirmation notes**: (only with independent local proof; requires human sign-off)",
        "- **Human decision**: (the final call — always made by a person)",
        "",
        "## Entries",
        "",
        "### CF-001",
        "",
        "- Hypothesis ID: CF-001",
        "- Test file: _(fill in)_",
        "- Command run: _(fill in)_",
        "- Result: _(fill in)_",
        "- Evidence summary: _(fill in)_",
        "- Rejection reason: _(fill if the invariant held)_",
        "- Confirmation notes: _(fill only with independent local proof)_",
        "- Human decision: _(human makes the final call)_",
        "",
    ]) + "\n"


def render_do_not_claim() -> str:
    out = [
        "# Do Not Claim",
        "",
        "> The boundary for everything in this pack. Read it before recording anything.",
        "",
    ]
    for line in m.DO_NOT_CLAIM:
        out.append(f"- {line}")
    out += [
        "",
        "## Why these boundaries exist",
        "",
        "ArkheionX is local and static. It maps where value moves and prioritizes where",
        "review attention is weakest. It does not run live, does not execute attacks, does",
        "not assign severity, and does not confirm vulnerabilities. Blind spot candidates,",
        "criticality potential, counterfactuals, and hypotheses are all review prompts. Only",
        "a human, with independent local proof, ever confirms a finding.",
        "",
    ]
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------
# Pack builder
# --------------------------------------------------------------------------
# Files are written in this fixed order so the manifest artifact list is stable.
_MARKDOWN_FILES = (
    "00-README.md", "01-review-map-summary.md", "02-blind-spots.md", "03-criticality-map.md",
    "04-counterfactuals.md", "05-agent-brief.md", "06-hypotheses.md", "07-evidence-log.md",
    "08-do-not-claim.md", "09-case-study-template.md",
)
_JSON_FILES = (
    "blind-spots.json", "criticality-map.json", "counterfactuals.json",
    "agent-brief.json", "hypotheses.json", "case-study.json", "manifest.json",
)

COMMANDS_REPRESENTED = ["review-map", "blind-spots", "criticality-map", "counterfactuals",
                        "agent-brief", "hypothesis-log", "case-study"]


def build_research_pack(rm: ReviewMap, root, out_dir, *, package_version: str,
                        source_files: int = 0, test_files: int = 0, write: bool = True) -> dict:
    """Build all pack payloads, write every file (unless ``write`` is False), and
    return the manifest + paths. When ``write`` is False no files are written and
    ``written`` maps each artifact to its intended (unwritten) path."""
    out_dir = Path(out_dir)

    blind_spots = build_blind_spot_map_from_review_map(rm, root, source_files=source_files, test_files=test_files)
    criticality = build_criticality_map_from_review_map(rm, root, source_files=source_files, test_files=test_files)
    counterfactuals = build_counterfactual_plan_from_review_map(rm, root, source_files=source_files, test_files=test_files)
    agent_brief = build_agent_brief_from_review_map(rm, root, source_files=source_files, test_files=test_files)
    hypotheses = build_hypothesis_log_from_review_map(rm, root)
    case_study = build_case_study_from_review_map(rm, root)

    contents = {
        "00-README.md": render_pack_readme(rm, package_version),
        "01-review-map-summary.md": render_review_map_summary(rm),
        "02-blind-spots.md": render.render_blind_spots_md(blind_spots),
        "03-criticality-map.md": render.render_criticality_map_md(criticality),
        "04-counterfactuals.md": render.render_counterfactuals_md(counterfactuals),
        "05-agent-brief.md": render_agent_brief_md(agent_brief),
        "06-hypotheses.md": render_hypothesis_log_md(hypotheses),
        "07-evidence-log.md": render_evidence_log_template(),
        "08-do-not-claim.md": render_do_not_claim(),
        "09-case-study-template.md": render_case_study_md(case_study),
    }
    json_payloads = {
        "blind-spots.json": blind_spots,
        "criticality-map.json": criticality,
        "counterfactuals.json": counterfactuals,
        "agent-brief.json": agent_brief,
        "hypotheses.json": hypotheses,
        "case-study.json": case_study,
    }

    written: dict[str, str] = {}
    for name in _MARKDOWN_FILES:
        written[name] = _write(out_dir / name, contents[name]) if write else str(out_dir / name)
    for name, payload in json_payloads.items():
        written[name] = _write(out_dir / name, json.dumps(payload, indent=2)) if write else str(out_dir / name)

    manifest = {
        "schema_version": m.SCHEMA_VERSION,
        "kind": m.KIND_RESEARCH_PACK_MANIFEST,
        "generated_at": rm.generated_at,
        "repo_path": rm.repo_path,
        "mode": rm.mode,
        "package_version": package_version,
        "commands_represented": list(COMMANDS_REPRESENTED),
        "artifacts": list(_MARKDOWN_FILES) + list(_JSON_FILES),
        "counts": {
            "blind_spot_candidates": len(blind_spots["candidates"]),
            "unknown_surfaces": len(blind_spots["unknown_surfaces"]),
            "criticality_surfaces": len(criticality["surfaces"]),
            "counterfactuals": len(counterfactuals["counterfactuals"]),
            "hypotheses": len(hypotheses["hypotheses"]),
        },
        "safety": {
            "local_static_only": True,
            "no_rpc": True,
            "no_live_chain": True,
            "no_secrets": True,
            "no_exploit_automation": True,
            "no_auto_submit": True,
            "no_severity": True,
            "no_vulnerability_claims": True,
            "vendor_agnostic": True,
            "human_review_required": True,
            "disclaimer": rm.safety.disclaimer,
        },
    }
    written["manifest.json"] = (
        _write(out_dir / "manifest.json", json.dumps(manifest, indent=2))
        if write else str(out_dir / "manifest.json"))

    return {"manifest": manifest, "written": written, "out_dir": str(out_dir)}
