"""Internal review package workspace layer (v3.6, additive, internal-only).

Provides deterministic package ID utilities and the review-package dataclasses
that later v3.6 agents use to collect artifacts, build manifests, validate, and
export reviewer-ready bundles. This package is internal infrastructure: it is not
a public API, adds no CLI command, changes no public artifact shape or schema,
and writes nothing to disk on import. It organizes local/static review context
only -- never confirmed vulnerabilities, final severity, or submission readiness.
"""
from __future__ import annotations

from .ids import (
    normalize_package_path,
    package_artifact_id,
    package_export_id,
    package_slug,
    package_validation_id,
    repo_fingerprint,
    review_package_id,
    review_workspace_id,
)
from .collector import (
    artifact_schema_for_kind,
    artifact_source_command,
    classify_artifact_path,
    collect_review_package_artifacts,
    default_artifacts_root,
    is_optional_artifact_kind,
    is_required_artifact_kind,
    iter_artifact_files,
    make_review_package_artifact,
    to_artifacts_relative_path,
    to_repo_relative_path,
)
from .manifest import (
    build_review_package_manifest,
    default_optional_artifact_kinds,
    default_required_artifact_kinds,
    manifest_to_dict,
    summarize_manifest_artifacts,
)
from .checksums import (
    build_checksum_map,
    checksum_artifact,
    checksum_artifact_file,
    checksum_manifest_artifacts,
    is_probable_checksum,
    normalize_checksum_path,
    sha256_bytes,
    sha256_file,
)
from .validate import (
    build_validation_result,
    derive_validation_status,
    scan_artifact_for_secret_patterns,
    validate_artifact_entries,
    validate_artifact_paths,
    validate_checksums,
    validate_manifest_shape,
    validate_required_artifacts,
    validate_review_package_manifest,
    validate_safety_boundary,
    validate_secret_patterns,
)
from .readme import build_limitations_text, build_reviewer_readme
from .builder import (
    ReviewPackageBuildResult,
    build_review_package,
    build_review_package_result_dict,
)
from .export import (
    archive_relative_path,
    create_review_package_zip,
    default_export_filename,
    default_export_path,
    default_exports_dir,
    export_review_package,
    is_exportable_package_file,
    iter_export_files,
    review_package_export_to_dict,
)
from .intelligence import (
    build_protocol_model_for_package,
    default_protocol_model_package_path,
    find_existing_protocol_model_artifact,
    include_protocol_model_sidecar,
    load_review_map_payload,
    protocol_model_to_package_dict,
    write_protocol_model_sidecar,
)
from .crossref import (
    collect_package_cross_references,
    extract_artifact_references,
    extract_protocol_model_ids,
    load_json_artifact,
    validate_package_cross_references,
)
from .model import (
    DEFAULT_REVIEW_PACKAGE_SAFETY_BOUNDARY,
    PACKAGE_DRAFT,
    PACKAGE_EXPORT_READY,
    PACKAGE_INVALID,
    PACKAGE_PARTIAL,
    PACKAGE_READY_FOR_HUMAN_REVIEW,
    SCHEMA_VERSION,
    ReviewPackageArtifact,
    ReviewPackageExport,
    ReviewPackageManifest,
    ReviewPackageValidationResult,
    ReviewWorkspace,
    to_dict,
)

__all__ = [
    "SCHEMA_VERSION",
    "DEFAULT_REVIEW_PACKAGE_SAFETY_BOUNDARY",
    "PACKAGE_DRAFT",
    "PACKAGE_PARTIAL",
    "PACKAGE_READY_FOR_HUMAN_REVIEW",
    "PACKAGE_INVALID",
    "PACKAGE_EXPORT_READY",
    "ReviewWorkspace",
    "ReviewPackageManifest",
    "ReviewPackageArtifact",
    "ReviewPackageValidationResult",
    "ReviewPackageExport",
    "to_dict",
    "normalize_package_path",
    "package_slug",
    "repo_fingerprint",
    "review_workspace_id",
    "review_package_id",
    "package_artifact_id",
    "package_validation_id",
    "package_export_id",
    "default_artifacts_root",
    "iter_artifact_files",
    "classify_artifact_path",
    "artifact_source_command",
    "artifact_schema_for_kind",
    "is_required_artifact_kind",
    "is_optional_artifact_kind",
    "to_repo_relative_path",
    "to_artifacts_relative_path",
    "make_review_package_artifact",
    "collect_review_package_artifacts",
    "default_required_artifact_kinds",
    "default_optional_artifact_kinds",
    "build_review_package_manifest",
    "summarize_manifest_artifacts",
    "manifest_to_dict",
    "sha256_bytes",
    "sha256_file",
    "normalize_checksum_path",
    "is_probable_checksum",
    "checksum_artifact",
    "checksum_artifact_file",
    "build_checksum_map",
    "checksum_manifest_artifacts",
    "validate_review_package_manifest",
    "validate_manifest_shape",
    "validate_required_artifacts",
    "validate_artifact_paths",
    "validate_artifact_entries",
    "validate_checksums",
    "validate_safety_boundary",
    "scan_artifact_for_secret_patterns",
    "validate_secret_patterns",
    "derive_validation_status",
    "build_validation_result",
    "build_reviewer_readme",
    "build_limitations_text",
    "ReviewPackageBuildResult",
    "build_review_package",
    "build_review_package_result_dict",
    "default_exports_dir",
    "default_export_filename",
    "default_export_path",
    "is_exportable_package_file",
    "iter_export_files",
    "archive_relative_path",
    "create_review_package_zip",
    "export_review_package",
    "review_package_export_to_dict",
    "default_protocol_model_package_path",
    "find_existing_protocol_model_artifact",
    "load_review_map_payload",
    "build_protocol_model_for_package",
    "protocol_model_to_package_dict",
    "write_protocol_model_sidecar",
    "include_protocol_model_sidecar",
    "extract_protocol_model_ids",
    "extract_artifact_references",
    "load_json_artifact",
    "collect_package_cross_references",
    "validate_package_cross_references",
]
