#!/usr/bin/env python3
"""Research dashboard for Arkheionx Vault.

Aggregates signals across metadata/registry.json and generated reports
into a single human-readable dashboard at reports/research_dashboard.md.

This is a derivative report. Counts are computed from the registry; the
script never invents data and never claims a verification level the
registry does not back up.

Usage:
    python scripts/research_dashboard.py             # write report
    python scripts/research_dashboard.py --check     # exit 1 if changed
    python scripts/research_dashboard.py --stdout    # print, no write
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REGISTRY = REPO / "metadata" / "registry.json"
OUT = REPO / "reports" / "research_dashboard.md"
MATURITY_REPORT = REPO / "reports" / "poc_maturity_index.md"
QUALITY_REPORT = REPO / "reports" / "poc_quality_matrix.md"


def _count(entries: list[dict], field: str, default: str = "unknown") -> Counter:
    return Counter(e.get(field, default) for e in entries)


def _bool_count(entries: list[dict], pred) -> int:
    return sum(1 for e in entries if pred(e))


def _table(rows: list[tuple[str, int]], headers: tuple[str, str]) -> list[str]:
    out = []
    out.append(f"| {headers[0]} | {headers[1]} |")
    out.append("|---|---|")
    for k, v in rows:
        out.append(f"| {k} | {v} |")
    return out


def _maturity_levels_from_report() -> dict[str, int]:
    """Best-effort parse of distribution table in maturity report."""
    if not MATURITY_REPORT.exists():
        return {}
    try:
        text = MATURITY_REPORT.read_text()
    except Exception:
        return {}
    out: dict[str, int] = {}
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("| L") and line.count("|") >= 4:
            parts = [p.strip() for p in line.split("|") if p.strip()]
            if len(parts) >= 3 and parts[0].startswith("L"):
                try:
                    out[parts[0]] = int(parts[2])
                except ValueError:
                    continue
    return out


def render(entries: list[dict]) -> str:
    n = len(entries)

    severity = _count(entries, "severity")
    category = _count(entries, "category")
    repro = _count(entries, "reproducibility")
    vstatus = _count(entries, "verification_status")
    aquality = _count(entries, "assertion_quality", default="none")
    chains = _count(entries, "chain")
    pub_rpc = _count(entries, "latest_public_rpc_status", default="not-tested")

    deterministic_confirmed = _bool_count(
        entries, lambda e: e.get("reproducibility") == "deterministic-confirmed"
        and e.get("verification_status") == "verified"
    )
    needs_verification = _bool_count(
        entries, lambda e: e.get("status") == "needs-verification"
    )
    archival_blocked = _bool_count(
        entries,
        lambda e: e.get("latest_public_rpc_status") == "public-rpc-not-archival"
        or e.get("verification_status") == "not-run-no-rpc",
    )
    weak_assertions = aquality.get("weak", 0) + aquality.get("none", 0)
    medium_assertions = aquality.get("medium", 0)
    strong_assertions = aquality.get("strong", 0)

    maturity = _maturity_levels_from_report()

    lines: list[str] = []
    lines.append("# Research Dashboard")
    lines.append("")
    lines.append(
        "Aggregated view of the Arkheionx Vault corpus. Generated by "
        "`scripts/research_dashboard.py`. Do not hand-edit."
    )
    lines.append("")
    lines.append(
        "All counts derive from `metadata/registry.json` and the generated "
        "reports in `reports/`. Anything not in those files is not on this "
        "page."
    )
    lines.append("")

    lines.append("## Corpus snapshot")
    lines.append("")
    lines.append(f"- Total PoCs: **{n}**")
    lines.append(
        f"- Deterministic-confirmed (verification report + verified status): "
        f"**{deterministic_confirmed}**"
    )
    lines.append(f"- Needs-verification entries: **{needs_verification}**")
    lines.append(f"- Archival-RPC blocked: **{archival_blocked}**")
    lines.append(
        f"- Strong static assertions: **{strong_assertions}**, "
        f"medium: **{medium_assertions}**, weak/none: **{weak_assertions}**"
    )
    lines.append("")

    if maturity:
        lines.append("## Maturity (from poc_maturity_index.md)")
        lines.append("")
        lines.extend(_table(
            [(k, maturity.get(k, 0)) for k in ("L0", "L1", "L2", "L3", "L4", "L5")],
            ("Level", "Count"),
        ))
        lines.append("")

    lines.append("## Assertion quality")
    lines.append("")
    lines.extend(_table(
        sorted(aquality.items(), key=lambda kv: -kv[1]),
        ("Quality", "Count"),
    ))
    lines.append("")

    lines.append("## Reproducibility")
    lines.append("")
    lines.extend(_table(
        sorted(repro.items(), key=lambda kv: -kv[1]),
        ("Reproducibility", "Count"),
    ))
    lines.append("")

    lines.append("## Verification status")
    lines.append("")
    lines.extend(_table(
        sorted(vstatus.items(), key=lambda kv: -kv[1]),
        ("Verification status", "Count"),
    ))
    lines.append("")

    lines.append("## Public RPC observations")
    lines.append("")
    lines.extend(_table(
        sorted(pub_rpc.items(), key=lambda kv: -kv[1]),
        ("Last public RPC outcome", "Count"),
    ))
    lines.append("")
    lines.append(
        "Public RPC observations are recorded for honesty, not as a verification "
        "level. `public-rpc-not-archival` is an RPC capability issue, not a PoC "
        "defect."
    )
    lines.append("")

    lines.append("## Severity")
    lines.append("")
    lines.extend(_table(
        sorted(severity.items(), key=lambda kv: -kv[1]),
        ("Severity", "Count"),
    ))
    lines.append("")

    lines.append("## Categories")
    lines.append("")
    lines.extend(_table(
        sorted(category.items(), key=lambda kv: -kv[1]),
        ("Category", "Count"),
    ))
    lines.append("")

    lines.append("## Chains")
    lines.append("")
    lines.extend(_table(
        sorted(chains.items(), key=lambda kv: -kv[1]),
        ("Chain", "Count"),
    ))
    lines.append("")

    lines.append("## Top next actions")
    lines.append("")
    lines.append(
        "1. Configure an archival mainnet RPC; re-run public-rpc-not-archival "
        "entries to clear the L3 boundary."
    )
    lines.append(
        "2. Strengthen `weak`/`none` assertions to `medium`+ on remaining entries "
        "before any new corpus additions."
    )
    lines.append(
        "3. Produce verification reports with real run output for entries that "
        "pass on archival RPC; promote `verification_status` to `verified` only "
        "when the report contains run output."
    )
    lines.append(
        "4. Begin first case study under `reports/case-studies/` once any entry "
        "clears L4."
    )
    lines.append("")

    lines.append("## Milestone progress")
    lines.append("")
    lines.append("Counts are honest snapshots. None of these gates is met yet.")
    lines.append("")
    lines.append("| Milestone | Bar | Current |")
    lines.append("|---|---|---|")
    lines.append(
        f"| 25 assertion-hardened | strong+medium ≥ 25 | "
        f"{strong_assertions + medium_assertions} |"
    )
    lines.append(
        f"| 25 archival-verified | deterministic-confirmed ≥ 25 | "
        f"{deterministic_confirmed} |"
    )
    lines.append(
        f"| 100 structured | total entries ≥ 100 | {n} |"
    )
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="Exit 1 if reports/research_dashboard.md would change.")
    ap.add_argument("--stdout", action="store_true",
                    help="Print to stdout, do not write.")
    args = ap.parse_args()

    reg = json.loads(REGISTRY.read_text())
    entries = reg.get("entries", [])
    text = render(entries)

    if args.stdout:
        sys.stdout.write(text)
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    current = OUT.read_text() if OUT.exists() else ""
    if current == text:
        print(f"ok: dashboard unchanged ({len(entries)} entries)")
        return 0

    if args.check:
        print(f"would update: {OUT.relative_to(REPO)}", file=sys.stderr)
        return 1

    OUT.write_text(text)
    print(f"updated: {OUT.relative_to(REPO)} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
