"""Internal local validation package (v3.7, additive, internal-only).

Foundational model and deterministic ID utilities for ingesting local Foundry /
local validation signals. This package is local/static only: it performs no RPC,
no fork-url behavior, and no live-chain calls; it handles no private keys and no
seed phrases; it runs no subprocess, calls no Foundry tool, and writes nothing to
disk. Importing it has no filesystem side effects.

Parser, builder, writer, CLI, and review-package integration are later v3.7 work.
"""
from __future__ import annotations

from .ids import (
    canonical_json_dumps,
    local_test_result_id,
    local_trace_receipt_id,
    local_validation_artifact_id,
    local_validation_run_id,
    local_validation_summary_id,
    normalize_id_path,
    repo_fingerprint,
    short_hash,
    slugify_token,
)
from .model import (
    ARTIFACT_KIND_RAW_JSON,
    ARTIFACT_KIND_RAW_TEXT,
    ARTIFACT_KIND_RUN,
    ARTIFACT_KIND_STDERR,
    ARTIFACT_KIND_STDOUT,
    ARTIFACT_KIND_SUMMARY,
    ARTIFACT_KIND_TEST_RESULT,
    ARTIFACT_KIND_TRACE,
    ARTIFACT_KIND_TRACE_RECEIPT,
    DEFAULT_LOCAL_VALIDATION_LIMITATIONS,
    DEFAULT_LOCAL_VALIDATION_SAFETY_BOUNDARY,
    LOCAL_VALIDATION_ARTIFACT_KINDS,
    LOCAL_VALIDATION_ERROR,
    LOCAL_VALIDATION_FAILED,
    LOCAL_VALIDATION_NOT_RUN,
    LOCAL_VALIDATION_PARTIAL,
    LOCAL_VALIDATION_PASSED,
    LOCAL_VALIDATION_RUNNING,
    LOCAL_VALIDATION_SKIPPED,
    SCHEMA_VERSION,
    SUPPORT_MANUAL_REVIEW_REQUIRED,
    SUPPORT_NONE,
    SUPPORT_TESTED,
    SUPPORT_TRACE_BOUND,
    TEST_ERROR,
    TEST_FAILED,
    TEST_PASSED,
    TEST_SKIPPED,
    TEST_UNKNOWN,
    TRACE_AVAILABLE,
    TRACE_NOT_AVAILABLE,
    TRACE_PARSE_ERROR,
    TRACE_PARTIAL,
    LocalTestResult,
    LocalTraceReceipt,
    LocalValidationArtifact,
    LocalValidationRun,
    LocalValidationSummary,
    local_validation_status_from_counts,
    to_dict,
)
from .parser import (
    FOUNDRY_JSON,
    FOUNDRY_TEXT,
    FOUNDRY_UNKNOWN,
    ParsedFoundryOutput,
    extract_duration_ms,
    extract_gas_used,
    foundry_status_to_local_status,
    parse_foundry_json_payload,
    parse_foundry_output,
    parse_foundry_text_output,
    parsed_foundry_output_to_dict,
    split_foundry_test_identifier,
)
from .builder import (
    LocalValidationBuildResult,
    assign_test_result_ids,
    build_local_validation_from_parsed,
    build_local_validation_run,
    build_local_validation_summary,
    extract_protocol_function_index,
    link_test_result_to_protocol,
    link_test_results_to_protocol,
    local_validation_build_result_to_dict,
)
from .writer import (
    LocalValidationWriteResult,
    build_local_validation_artifact_index,
    default_local_validation_output_root,
    ensure_safe_output_root,
    json_dump_deterministic,
    local_validation_write_result_to_dict,
    safe_relative_to_repo,
    write_local_validation_artifacts,
)

__all__ = [
    "SCHEMA_VERSION",
    # dataclasses
    "LocalValidationRun",
    "LocalTestResult",
    "LocalTraceReceipt",
    "LocalValidationArtifact",
    "LocalValidationSummary",
    # serializer + status helper
    "to_dict",
    "local_validation_status_from_counts",
    # run statuses
    "LOCAL_VALIDATION_NOT_RUN",
    "LOCAL_VALIDATION_RUNNING",
    "LOCAL_VALIDATION_PASSED",
    "LOCAL_VALIDATION_FAILED",
    "LOCAL_VALIDATION_PARTIAL",
    "LOCAL_VALIDATION_ERROR",
    "LOCAL_VALIDATION_SKIPPED",
    # test statuses
    "TEST_PASSED",
    "TEST_FAILED",
    "TEST_SKIPPED",
    "TEST_ERROR",
    "TEST_UNKNOWN",
    # trace statuses
    "TRACE_NOT_AVAILABLE",
    "TRACE_AVAILABLE",
    "TRACE_PARTIAL",
    "TRACE_PARSE_ERROR",
    # evidence-support signals
    "SUPPORT_NONE",
    "SUPPORT_TESTED",
    "SUPPORT_TRACE_BOUND",
    "SUPPORT_MANUAL_REVIEW_REQUIRED",
    # artifact kinds
    "ARTIFACT_KIND_RUN",
    "ARTIFACT_KIND_TEST_RESULT",
    "ARTIFACT_KIND_TRACE_RECEIPT",
    "ARTIFACT_KIND_SUMMARY",
    "ARTIFACT_KIND_STDOUT",
    "ARTIFACT_KIND_STDERR",
    "ARTIFACT_KIND_RAW_JSON",
    "ARTIFACT_KIND_RAW_TEXT",
    "ARTIFACT_KIND_TRACE",
    "LOCAL_VALIDATION_ARTIFACT_KINDS",
    # safety + limitations
    "DEFAULT_LOCAL_VALIDATION_SAFETY_BOUNDARY",
    "DEFAULT_LOCAL_VALIDATION_LIMITATIONS",
    # id helpers
    "canonical_json_dumps",
    "short_hash",
    "normalize_id_path",
    "slugify_token",
    "repo_fingerprint",
    "local_validation_run_id",
    "local_test_result_id",
    "local_trace_receipt_id",
    "local_validation_artifact_id",
    "local_validation_summary_id",
    # parser
    "ParsedFoundryOutput",
    "FOUNDRY_JSON",
    "FOUNDRY_TEXT",
    "FOUNDRY_UNKNOWN",
    "parse_foundry_output",
    "parse_foundry_json_payload",
    "parse_foundry_text_output",
    "parsed_foundry_output_to_dict",
    "foundry_status_to_local_status",
    "extract_gas_used",
    "extract_duration_ms",
    "split_foundry_test_identifier",
    # builder
    "LocalValidationBuildResult",
    "build_local_validation_from_parsed",
    "build_local_validation_run",
    "assign_test_result_ids",
    "build_local_validation_summary",
    "extract_protocol_function_index",
    "link_test_result_to_protocol",
    "link_test_results_to_protocol",
    "local_validation_build_result_to_dict",
    # writer
    "LocalValidationWriteResult",
    "write_local_validation_artifacts",
    "local_validation_write_result_to_dict",
    "default_local_validation_output_root",
    "ensure_safe_output_root",
    "safe_relative_to_repo",
    "json_dump_deterministic",
    "build_local_validation_artifact_index",
]
